### ISSUE TITLE
Repository - trouble with cascade persist 

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#212]
Hi, 
I have another stranch behaviour with cascade collection storing.

This following code doesn't update items:

```php
$items = $order->items->get()->findBy([..]);
foreach ($items as $item) {
   $item->name = 'xyz';
}
$orderRepository->persistAndFlush($order);
```

And this works:

```php
$items = $order->items;
foreach ($items as $item) {
   $item->name = 'xyz';
}
$orderRepository->persistAndFlush($order);
```

@hrach Is it right behaviour? Did items in first example lost their reference to main order entity? Or is it a bug?

More then that, this behaviour is in 2.2.3 but in 2.2.0 it seems to work.

**Comment by hrach** [comment]
Bug! Will try to fix!

**Comment by hrach** [comment]
Well, yesterday I've spent a hour or two with fixing this. Sadly, this is pretty bad bug, which require a lot of internal changes.

- the changes will be huge, so I don't feel ok to release them as 2.2.4.
- the changes will be huge in master, so I'm scary of porting them to 2.2 branch

I'm thinking if it's ok for you to do persist manually, or stick with 2.2.0, though, you probably miss the another bugfix for issue you have reported.

**Comment by f3l1x** [comment]
Ou, well, that's sad. 

I'm with it if it will be in master and version 2.3. Don't worry, looking forward to patch. :-)

**Comment by hrach** [comment]
> I'm with it if it will be in master and version 2.3.

That's another option, which actually means to port from 3.0. Thath's hard. Will see what I can do.

**Comment by f3l1x** [comment]
Good luck. :-) I'm master of bug-reporting :smiley:

**Comment by hrach** [comment]
After many days spending fixing this (still not pubslihed in master), I came to conclusion that the best will be:

- not fixing this in 2.2, since there is an easy workaround,
- mainly because the fix is pretty complex and reverting another fix which revealed this bug would mean reintroducing a major performance issue which would not have a workaround.

I'm really sorry for this situation.  I will mention this issue in the next patch stable release as known issue.

Workaround: 
```php
$items = $order->items->get()->findBy([..]);
foreach ($items as $item) {
   $item->name = 'xyz';
   $orderRepository->getModel()->persist($item);
}
$orderRepository->persistAndFlush($order);
```

**Comment by f3l1x** [comment]
@hrach It's ok, I'm going to upgrade to PHP7.1 where it's possible, elsewhere I will use workaround.

**Comment by hrach** [comment]
Oh, I've finally discovered the nature of the bugs and working on the proper solution. I was misled by another bug which I've discovered during writing more tests for ManyHasMany relationship.

**Comment by f3l1x** [comment]
Great. Where is the catch?

**Comment by hrach** [comment]
The catch is to do this in nice & clean way. The tracking of fetched entities has to be done for all relationship entities, but should not be done on relationshipmapper layer, because it is indenpendent from that layer, and should not be done somehow conditionaly in IColleciton from the same reasons. There for some new api will be needed to allow the relationship connect the the resulst of ICollection, which may be actually fetched later than the creating of relationship collection.
