### ISSUE TITLE
Wrong error message if repository not exists

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#301]
I am getting error message `Relationship {1:m} in Model\Entity\PricelistEntity::$allPrices points to unknown 'Model\Entity\PriceEntity' entity.` event if this Entity exists, but there is no `PriceReposiotry`. It takes me almost 1 hour to find what is problem.

Consider to use more accurate error message that entity does not have repository.

**Comment by hrach** [comment]
Thank you for this useful experience report. What was your main problem? Not knowing that you have to define a repository or that "uknown" means something different that "not found" (e.g. some other problem than the classic autoloader thing)?

**Comment by mabar** [comment]
Unkown usually means that class cannot be reached by autoloading so it would be nice to explain, why is unkown. I agree that it should explain a repository is required. Exceptions which tell me how to fix a problem are best.

**Comment by hrach** [comment]
> Unkown usually means
I disagree. Such messages are Class not found. This doesn't say the class was not found. The wording was chosen for purpose, but obviously it is not sufficient.

> Exceptions which tell me how to fix a problem are best.
Agreed. Though, there is no easy way to tell what is wrong. Orm can't know if you didn't registered it's repository, didn't create its repository, or didn't returned all known entities in repositories' static method. Probably will have to prioritize some suggestions, that's why I'm asking what was the main misunderstanding :)
