### ISSUE TITLE
How to annotate property that is managed by database itself

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#349]
hi,

I have properties `createdAt` and `updatedAt` which values are managed by DB by `CURRENT_TIMESTAMP`:
```
/**
* @property-read DateTimeImmutable $createdAt {virtual}
 * @property-read DateTimeImmutable $updatedAt {virtual}
*/
class UserEntity extends Entity
...
```
Problem is that I must have `{virtual}` annotation there otherwise I am getting `Property UserEntity::$createdAt is not set.` but when it is `{virtual}` I can not access to value even using `getRawValue()` because I am getting `Maximum function nesting level of '256' reached, aborting!` because `getRawValue()` is calling itself.

So do somebody know how to hack this? I would expect that `@property-read` will not raise `Property is not set.` exception. So maybe this is bug. But I need it somehow solve it for now because it is blocking me.

Thanks

**Comment by hrach** [comment]
Hi, first, some fundamental rules:

1) Do the most in the orm layer. If not crucially needed, create the datetime in the PHP. Mainly because of consistency, other datetime values will be probably filled by PHP (e.g. users' verified time). Of couse all this handling could be done in database layer, but this is quite opposite what we try to achieve with ORMs.

2)  Be true about actual property types. The entity exists in Php in invalid state, until you persist it. This is how Orm and developers see it. If you pass the entity somewhere, it will not be fully usable. So, createdAt should be annotated with with `|null` type annotation. That's it. I understand it may be difficult to read the value after persist without non-pleasant checks. You may add your own getter that will check for nullability and return non-nullable datetime.

----

To propagate changes from db, you may use:

- ignore the change for "now", e.g. in other request it will load the proper createdAt value 
- use `IPersistAutoupdateMapper` interface and implement method to say which columns you wanna update; this works for Postgres - where it uses `RETURNING` syntax, and for MySQL - where it uses a separate query; [see test implementation](https://github.com/nextras/orm/blob/cf4ad4edfdcc514fbf0a6e539eafe3e4b60b5291/tests/inc/model/bookCollection/BookCollectionsMapper.php)
- use [Model::refresh()](https://nextras.org/orm/docs/3.1/model#toc-refresh)
