### ISSUE TITLE
Using enum with bool property

### ISSUE THREAD

**Issue by Hologos** [nextras/orm#374]
Hi,

I found out that using enum on `bool` property causes InvalidArgumentException. Is it intended behaviour? The reason I use constants is that it makes the code more readable. Using enum on the property is maybe redundant since the only allowed values are `true` and `false`. I'd like to know your opinion. Thanks.

```php
/**
 * @property int                  $id                    {primary}
 * ...
 * @property bool                 $approved              {enum self::STATE_*}
 * ...
 */
class Customer extends Entity
{
    const STATE_APPROVED = true,
          STATE_NOT_APPROVED = false;
}
```

**Comment by JanTvrdik** [comment]
I usually prefer using nullable `DateTimeImmutable` in this case, i.e.

```php
/**
 * @property null|DateTimeImmutable $approvedAt
 */
class Customer extends Entity
{
}
```

**Comment by hrach** [comment]
@Hologos could you post a stack trace and a version you are using? this should work.

**Comment by Hologos** [comment]
[Here is the trace](https://github.com/nextras/orm/files/4158234/trace.html.zip) and the version is v3.1.0.

**Comment by hrach** [comment]
Yeah, of course, the error is valid. Storage returns you an int and that is validated during initialization. Since you are using enum - we can't do coercion prior to validation, since enums can have multiple types combined. If you would like to use it like this, you have to do the conversion in mapper layer using setMapping.
